2020-12-21 09:28:57,258 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:38] - DEBUG: [Errno 2] No such file or directory: '../db/60004036_20200930（外罗）.cv'
2020-12-21 09:30:16,326 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:38] - DEBUG: [Errno 2] No such file or directory: '../db/60004036_20200930（外罗）.cv'
2020-12-22 08:41:16,401 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:25] - DEBUG: '60001'
2020-12-22 10:09:49,678 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:169] - DEBUG: local variable 'date' referenced before assignment
2020-12-22 10:10:05,229 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:169] - DEBUG: local variable 'date' referenced before assignment
2020-12-22 10:11:27,460 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:170] - DEBUG: local variable 'date' referenced before assignment
2020-12-22 10:11:39,835 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:169] - DEBUG: local variable 'date' referenced before assignment
2020-12-22 10:12:38,147 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:169] - DEBUG: local variable 'date' referenced before assignment
2020-12-22 10:13:20,460 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:170] - DEBUG: local variable 'date' referenced before assignment
2020-12-22 10:13:46,272 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:171] - DEBUG: local variable 'date' referenced before assignment
2020-12-22 10:14:11,725 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:171] - DEBUG: list indices must be integers or slices, not str
2020-12-22 10:14:27,023 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:172] - DEBUG: list indices must be integers or slices, not str
2020-12-22 10:14:38,788 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:172] - DEBUG: list indices must be integers or slices, not str
2020-12-22 10:14:51,483 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:172] - DEBUG: list indices must be integers or slices, not str
2020-12-22 10:16:15,115 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:171] - DEBUG: list indices must be integers or slices, not str
2020-12-22 10:17:39,260 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:171] - DEBUG: list indices must be integers or slices, not str
2020-12-22 10:18:11,485 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:172] - DEBUG: list indices must be integers or slices, not str
2020-12-22 10:18:26,257 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:170] - DEBUG: list indices must be integers or slices, not str
2020-12-22 10:19:05,183 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:170] - DEBUG: list indices must be integers or slices, not str
2020-12-22 10:19:39,092 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:170] - DEBUG: list indices must be integers or slices, not str
2020-12-22 10:19:59,430 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:170] - DEBUG: list indices must be integers or slices, not str
2020-12-22 10:21:04,355 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:170] - DEBUG: list indices must be integers or slices, not str
2020-12-22 10:21:14,969 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:170] - DEBUG: list indices must be integers or slices, not str
2020-12-22 10:31:48,148 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:174] - DEBUG: '60004036'
2020-12-22 10:42:55,287 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:169] - DEBUG: get_df() missing 1 required positional argument: 'file'
2020-12-22 10:48:46,631 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:167] - DEBUG: list index out of range
2020-12-22 10:49:08,977 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:167] - DEBUG: list index out of range
2020-12-22 10:49:57,193 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:168] - DEBUG: list index out of range
2020-12-22 10:50:17,135 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:168] - DEBUG: list index out of range
2020-12-22 10:50:37,460 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:168] - DEBUG: handle_csv() missing 1 required positional argument: 'usecols'
2020-12-22 10:51:00,584 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:168] - DEBUG: handle_csv() missing 1 required positional argument: 'usecols'
2020-12-22 10:51:12,292 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:168] - DEBUG: handle_csv() missing 1 required positional argument: 'usecols'
2020-12-22 10:51:22,236 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:168] - DEBUG: handle_csv() missing 1 required positional argument: 'usecols'
2020-12-22 10:51:46,165 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:168] - DEBUG: handle_csv() missing 1 required positional argument: 'usecols'
2020-12-22 10:52:15,584 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:169] - DEBUG: handle_csv() missing 1 required positional argument: 'usecols'
2020-12-22 10:53:37,922 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:169] - DEBUG: [Errno 2] No such file or directory: '.\\data\\60004036_20200930.csv'
2020-12-22 10:55:11,419 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:168] - DEBUG: [Errno 2] No such file or directory: '.\\data\\60004036_20200930.csv'
2020-12-22 10:55:48,554 - C:/Users/A07417/PycharmProjects/MyOFP2.0/core/core.py[line:169] - DEBUG: [Errno 2] No such file or directory: '.\\data\\60004020_20200711.csv'
